# Generated by Django 4.2.1 on 2023-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='order_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='pay_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='sign',
            field=models.CharField(max_length=400),
        ),
    ]
